development:
  adapter: postgresql
  encoding: utf8
  database: custo_viagem_development
  username: victorcsv
  password: 
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: utf8
  database: custo_viagem_test
  username: victorcsv
  password: 

production:
  adapter: postgresql
  encoding: utf8
  database: custo_viagem_production
  username: victorcsv
  password: victorcsv
