development:
  adapter: sqlite3
  encoding: utf8
  database: db/development.sqlite3

test:
  adapter: postgresql
  encoding: utf8
  database: custo_viagem_test
  username: victorcsv
  password: 

production:
  adapter: postgresql
  encoding: utf8
  database: custo_viagem_production
  username: victorcsv
  password: victorcsv
